name: Deploy to Firebase

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Firebase CLI
      uses: FirebaseExtended/action-hosting-deploy@v0.4.1
      with:
        firebase_version: '9.23.0'
    
    - name: Build
      run: |
        npm start
    
    - name: Deploy to Firebase
      run: |
        firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
